databases:
  - name: Butterfly peak
    databaseName: butterfly_peak
    user: butterfly_peak_user
    plan: free

services:
  - type: web
    plan: free
    name: bbcare
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: postgres://butterfly_peak_user:V8BGsJdFp7uZMd0frmCogaPitOR5LD8E@dpg-cnt8h1779t8c73ac7umg-a/butterfly_peak
        fromDatabase:
          name: Butterfly peak
          property: connectionString
      - key: 66cc5f9fba8dd9059ca4cb13564d1ff8
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default