databases:
  - name: bbcaredb
    databaseName: bbcaredb
    user: bbcaredb_user
    plan: free

services:
  - type: web
    plan: free
    name: bbcare
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bbcaredb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false